// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfwClPKjTMSxP1D_2Kvrqkk88KIbV42AI',
    appId: '1:144857749466:web:f1cf69dd1b2ff0d60c52e3',
    messagingSenderId: '144857749466',
    projectId: 'todolistapp-4aa88',
    authDomain: 'todolistapp-4aa88.firebaseapp.com',
    storageBucket: 'todolistapp-4aa88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKEdT3aHbTskrkM6C4Gj5K9kv4bNBQtew',
    appId: '1:144857749466:android:9c1f39675197ec7e0c52e3',
    messagingSenderId: '144857749466',
    projectId: 'todolistapp-4aa88',
    storageBucket: 'todolistapp-4aa88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq3P6FkAcjycyvdjg0YP_Nw5bRtlnyMrc',
    appId: '1:144857749466:ios:dfe18c54d86d15410c52e3',
    messagingSenderId: '144857749466',
    projectId: 'todolistapp-4aa88',
    storageBucket: 'todolistapp-4aa88.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq3P6FkAcjycyvdjg0YP_Nw5bRtlnyMrc',
    appId: '1:144857749466:ios:dfe18c54d86d15410c52e3',
    messagingSenderId: '144857749466',
    projectId: 'todolistapp-4aa88',
    storageBucket: 'todolistapp-4aa88.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfwClPKjTMSxP1D_2Kvrqkk88KIbV42AI',
    appId: '1:144857749466:web:f949e6382ec058640c52e3',
    messagingSenderId: '144857749466',
    projectId: 'todolistapp-4aa88',
    authDomain: 'todolistapp-4aa88.firebaseapp.com',
    storageBucket: 'todolistapp-4aa88.appspot.com',
  );
}
